name: Python CLI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v4

    # Étape 2 : Configurer Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Étape 4 : Vérifier la qualité du code avec flake8
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 blkpy --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 blkpy --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Étape 5 : Tester la commande CLI
    - name: Test CLI functionality
      run: |
        blkpy --help
        blkpy -v /dev/null

   
